//第一列是默认名称，从第二列开始的都是别名
ARRAY 
BIGINT INT8 LONG 
BINARY RAW BYTEA LONG RAW 
BLOB TINYBLOB MEDIUMBLOB LONGBLOB IMAGE OID 
BOOLEAN BIT BOOL 
CHAR CHARACTER NCHAR 
CLOB TINYTEXT TEXT MEDIUMTEXT LONGTEXT NTEXT NCLOB 
DATE 
DECIMAL DEC 
DOUBLE DOUBLE PRECISION 
FLOAT FLOAT8 
GEOMETRY 
IDENTITY BIGSERIAL 
INTEGER INT MEDIUMINT INT4 SIGNED 
LONGVARBINARY 
LONGVARCHAR LONGNVARCHAR 
NULL 
NUMERIC NUMBER 
OTHER OBJECT JAVA_OBJECT 
REAL FLOAT4 
RESULT_SET
SERIAL 
SMALLINT YEAR INT2 
TIME 
TIMESTAMP DATETIME DATETIME2 SMALLDATETIME 
TIMESTAMP WITH TIMEZONE 
TIMESTAMP_UTC 
TINYINT 
UUID 
VARBINARY 
VARCHAR VARCHAR2 NVARCHAR NVARCHAR2 VARCHAR_CASESENSITIVE CHARACTER VARYING TID 
VARCHAR_IGNORECASE 