与三个表有关:
LOBS
LOB_DATA
LOB_MAP


LOBS:
-------------
CREATE CACHED TABLE IF NOT EXISTS INFORMATION_SCHEMA.LOBS
	(ID BIGINT PRIMARY KEY, BYTE_COUNT BIGINT, TABLE INT) HIDDEN


LOB_DATA:
-------------
CREATE CACHED TABLE IF NOT EXISTS INFORMATION_SCHEMA.LOB_DATA
	(BLOCK BIGINT PRIMARY KEY, COMPRESSED INT, DATA BINARY) HIDDEN


LOB_MAP:
-------------
CREATE CACHED TABLE IF NOT EXISTS INFORMATION_SCHEMA.LOB_MAP
	(LOB BIGINT, SEQ INT, POS BIGINT, HASH INT, BLOCK BIGINT, PRIMARY KEY(LOB, SEQ)) HIDDEN

LOBS表的ID字段和LOB_MAP的LOB字段对应，值一样(就是lobId)


另外还有两个索引:

在LOBS表上的索引: INDEX_LOB_TABLE
-------------
CREATE INDEX IF NOT EXISTS INFORMATION_SCHEMA.INDEX_LOB_TABLE ON INFORMATION_SCHEMA.LOBS(TABLE)

在LOB_MAP表上的索引: INDEX_LOB_MAP_DATA_LOB
-------------
CREATE INDEX IF NOT EXISTS INFORMATION_SCHEMA.INDEX_LOB_MAP_DATA_LOB ON INFORMATION_SCHEMA.LOB_MAP(BLOCK, LOB)



以上内容对应源代码见: org.h2.store.LobStorage.init()

